version: "3"

services:

  fb-baseline:
    image: ${FB_BASELINE_IMAGE}
    volumes:
      - log-volume:/logs:ro
      - ${FB_BASELINE_CONFIG}:/fluent-bit/etc/fluent-bit.conf:ro

  fb-delta:
    # image: ${FB_DELTA_IMAGE}
    build:
      context: https://github.com/fluent/fluent-bit.git#input-thread-2
      dockerfile: dockerfiles/Dockerfile
    volumes:
      - log-volume:/logs:ro
      - ${FB_DELTA_CONFIG}:/fluent-bit/etc/fluent-bit.conf:ro
    environment:
      FLB_DEV_RB_MS: 100

  data-generator:
    # build: https://github.com/lecaros/flog.git
    # command: --overwrite --loop --output /logs/test.log --rate ${FLOG_RATE} --type log
    image: fluentbitdev/fluent-bit-ci:benchmark
    command: bash /data-gen-multi.sh
    volumes:
      - log-volume:/logs:rw
      - ./data-gen-multi.sh:/data-gen-multi.sh:ro
    environment:
      LOG_PREFIX: test
      LOG_COUNT: 1
      LOG_RATE: 20000
      LOG_SIZE: 1000

  multifile-data-generator:
    image: fluentbitdev/fluent-bit-ci:benchmark
    command: bash /data-gen-multi.sh
    volumes:
      - log-volume:/logs:rw
      - ./data-gen-multi.sh:/data-gen-multi.sh:ro
    environment:
      LOG_PREFIX: multi
      LOG_COUNT: 100
      LOG_RATE: 20
      LOG_SIZE: 1000

volumes:
  log-volume:
