---
name: Run these tests on a VM
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  VM_NAME: perf-test
jobs:
  setup-vm-instance:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_LTS_SA }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Set up defaults
        run: |
          gcloud config set compute/zone us-east1-c
        shell: bash

      - name: Destroy any previous VM
        continue-on-error: true
        run: |
          gcloud compute instances delete "$VM_NAME" -q || true
        shell: bash

      - name: Deploy VM
        run: |
          gcloud compute instances create "$VM_NAME" --image="perf-test-ubuntu-2004"
            --metadata=SELF_DESTRUCT_INTERVAL_MINUTES=720
          sleep 30
        shell: bash

      - name: Wait for SSH access
        timeout-minutes: 2
        run: |
          echo "Waiting for SSH access to $VM_NAME..."
          until gcloud compute ssh "$VM_NAME" -q --command="true" 2> /dev/null; do
            echo -n '.'
            sleep 1
          done
          echo
          echo "Successfully connected to $VM_NAME"
          gcloud compute ssh "$VM_NAME" -q --command="sudo usermod -aG docker $USER"
          gcloud compute ssh "$VM_NAME" -q --command="mkdir -p ${{ github.repository }} && git clone https://github.com/${{ github.repository }} ${{ github.repository }}"
        shell: bash

  # Allows us just to re-run here
  run-tests-on-vm-instance:
    runs-on: ubuntu-latest
    needs:
      - setup-vm-instance
    steps:
      - name: Run tests on VM
        timeout-minutes: 30
        run: |
          gcloud compute ssh "$VM_NAME" -q --command="cd ${{ github.repository }}/compose && ./run.sh"
          gcloud compute scp --force-key-file-overwrite --recurse "$VM_NAME":~/${{ github.repository }}/compose/output output
        shell: bash

      - name: Upload any results
        uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/

      - name: Get debug information if possible on failure
        continue-on-error: true
        if: failure()
        timeout-minutes: 5
        run: |
          gcloud compute ssh "$VM_NAME" -q --command="sudo grep startup-script /var/log/messages" || true
          gcloud compute ssh "$VM_NAME" -q --command="sudo grep startup-script /var/log/syslog" || true
          gcloud compute ssh "$VM_NAME" -q --command="rpm -qa" || true
          gcloud compute ssh "$VM_NAME" -q --command="dpkg -l" || true
          gcloud compute ssh "$VM_NAME" -q --command="systemctl status" || true
          gcloud compute ssh "$VM_NAME" -q --command="ls -lR" || true
        shell: bash

      - name: Destroy VM
        # Does not run on failure for debug within the self-destruct interval or until next run
        run: |
          gcloud compute instances delete "$VM_NAME" -q
        shell: bash
