---
name: Update VM image
on:
  push:
    branches:
      - main
    paths:
      - packer/

jobs:
  create-vm-instance:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt-get update
          sudo apt-get install -y packer vagrant virtualbox
        shell: bash

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_LTS_SA }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Build instance
        run: |
          packer build -force -color=false ./packer.json
        shell: bash
        working-directory: packer
